[versions]
compileSdk = "33"
metricsPerformance = "1.0.0-alpha04"
minimumSdk = "26"
targetSdk = "33"
appVersionCode = "80"

assertk = "0.26.1"
compose-compiler = "1.4.7"
compose = "1.4.3"
hilt = "2.46.1"
compose-bom = "2023.06.01"
benchmark-macro-junit4 = "1.2.0-alpha16"
composeLintChecks = "1.2.0"
googlePlayServices = "4.3.15"
kotlinxCollectionsImmutable = "0.3.5"
compose-multiplatform = "1.4.1"

kalendar = "1.3.1"
kotestRunnerJunit5 = "5.6.2"
kotlinInjectRuntime = "0.6.1"
kotlinInjectCompilerKsp = "0.6.1"
material = "1.4.3"
material3 = "1.1.1"
gradle = "8.0.2"
detekt = "1.23.0"
ktlint = "11.4.2"
kotlin = "1.8.21"
ksp = "1.8.21-1.0.11"
coroutines = "1.7.1"
okhttp = "5.0.0-alpha.11"
coil = "2.4.0"
androidxtest = "1.5.2"
media3 = "1.0.2"
pagingCompose = "1.0.0-alpha20"
androidxnavigation = "2.6.0"
firebase = "32.1.1"
firebase-plugin = "2.9.6"
moshi = "1.15.0"
retrofit = "2.9.0"
accompanist = "0.30.1"
work = "2.8.1"
room = "2.5.2"
lifecycle = "2.6.1"
sqldelight = "2.0.0-rc01"
dokka = "1.8.20"
kmpNativeCoroutines = "0.13.3"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
com-google-android-material-material = "1.9.0"
runner = "1.0.2"
com-android-support-test-espresso-espresso-core = "3.0.2"
appcompat-v7 = "28.0.0"

[libraries]
androidx-metrics-performance = { module = "androidx.metrics:metrics-performance", version.ref = "metricsPerformance" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
assertk-common = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "composeLintChecks" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-data = { module = "androidx.compose.ui:ui-tooling-data" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-unit = { module = "androidx.compose.ui:ui-unit" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-iconsextended = { module = "androidx.compose.material:material-icons-extended" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-material-material2 = { module = "androidx.compose.material:material", version.ref = "material" }
compose-material-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
compose-material-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

#Kotlin Libs
kalendar = { module = "com.himanshoe:kalendar", version.ref = "kalendar" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotestRunnerJunit5" }
kotlin-inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInjectRuntime" }
kotlin-inject-compiler-ksp = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInjectCompilerKsp" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-metadataJvm = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.6.2"

#Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-analyticsKts = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-crashlytics-gradlePlugin = "com.google.firebase:firebase-crashlytics-gradle:2.9.6"

#Moshi
square-moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
square-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
square-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

#Sql Delight
square-sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
square-sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
square-sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
square-sqldelight-driver-sqlite = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
square-sqldelight-coroutinesExt = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

#Leak Canary
square-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.11"

#OkHttp
square-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
square-okhttp-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
square-okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

#Retrofit
square-retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
square-retrofit2-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
square-retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

#Accompanist
accompanist-insets = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-systemUiController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-native = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1"

kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-core = "androidx.core:core-ktx:1.10.1"
androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
androidx-fragment = "androidx.fragment:fragment-ktx:1.6.0"
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation-ktx:1.0.0-alpha03"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-palette = "androidx.palette:palette-ktx:1.0.0"
androidx-datastore-preferencesCore = "androidx.datastore:datastore-preferences-core:1.0.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-test-ext-junit = "androidx.test.ext:junit:1.1.5"

#Work
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "work" }
androidx-work-gcm = { module = "androidx.work:work-gcm", version.ref = "work" }

#Dagger Hilt
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
dagger-hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-rxJava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
androidx-room-guava = { module = "androidx.room:room-guava", version.ref = "room" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-rxJava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }


#Google
google-playservices-gradlePlugin = "com.google.gms:google-services:4.3.15"
google-playservices-core = "com.google.android.play:core-ktx:1.8.1"
google-playservices-location = "com.google.android.gms:play-services-location:21.0.1"
google-material = "com.google.android.material:material:1.9.0"

#Androidx
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxnavigation" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "androidxnavigation" }
androidx-test-core = { module = "androidx.test:core-ktx", version.ref = "androidxtest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxtest" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxtest" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxtest" }
androidx-test-uiAutomator = "androidx.test.uiautomator:uiautomator:2.2.0"

#Media 3
#Media3
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-exoplayer-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
androidx-media3-exoplayer-rtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3" }
androidx-media3-exoplayer-ima = { module = "androidx.media3:media3-exoplayer-ima", version.ref = "media3" }


androidx-media3-workmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "media3" }
androidx-media3-datasource-cronet = { module = "androidx.media3:media3-datasource-cronet", version.ref = "media3" }
androidx-media3-datasource-okhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }
androidx-media3-datasource-rtmp = { module = "androidx.media3:media3-datasource-rtmp", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3" }
androidx-media3-extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3" }
androidx-media3-cast = { module = "androidx.media3:media3-cast", version.ref = "media3" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3" }
androidx-media3-testUtils = { module = "androidx.media3:media3-test-utils", version.ref = "media3" }
androidx-media3-testUtils-robolectric = { module = "androidx.media3:media3-test-utils-robolectric", version.ref = "media3" }
androidx-media3-database = { module = "androidx.media3:media3-database", version.ref = "media3" }
androidx-media3-decoder = { module = "androidx.media3:media3-decoder", version.ref = "media3" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3" }

androidx-test-espressoCore = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-espressoWeb = "androidx.test.espresso:espresso-web:3.5.1"
androidx-hilt-work = "androidx.hilt:hilt-work:1.0.0"
androidx-hilt-compiler = "androidx.hilt:hilt-compiler:1.0.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
androidx-hilt-navigation-fragment = "androidx.hilt:hilt-navigation-fragment:1.0.0"

affectedmoduledetector = "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.2.1"

android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

# Lone wolves
desugaring = "com.android.tools:desugar_jdk_libs:2.0.3"
snapper = "dev.chrisbanes.snapper:snapper:0.3.0"
lottie-compose = "com.airbnb.android:lottie-compose:6.0.1"
falcon = "com.jraska:falcon:2.2.0"
assertJ = "org.assertj:assertj-core:3.24.2"
screengrab = "tools.fastlane:screengrab:2.1.1"
mockk = "io.mockk:mockk:1.13.5"
turbine = "app.cash.turbine:turbine:1.0.0"
timber = "com.jakewharton.timber:timber:5.0.1"
detekt-formatting = "io.gitlab.arturbosch.detekt:detekt-formatting:1.23.0"
slack-compose-lint = "com.slack.lint.compose:compose-lint-checks:1.2.0"
napier = "io.github.aakira:napier:2.6.1"
junit = "junit:junit:4.13.2"
datePickerTimeline = "com.github.Rafsanjani:datepickertimeline:0.7.1"
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit115 = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material-material" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
com-android-support-test-espresso-espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "com-android-support-test-espresso-espresso-core" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompat-v7" }

[bundles]
androidx-compose-implementation = [
    "compose-ui-ui",
    "compose-ui-util",
    "compose-ui-tooling",
    "compose-ui-tooling-data",
    "compose-ui-tooling-preview",
    "compose-foundation-foundation",
    "compose-foundation-foundation",
    "compose-foundation-layout",
    "compose-material-iconsextended",
    "compose-animation-animation",
    "androidx-paging-compose",
    "compose-material-material3",
    "compose-material-material3-windowSizeClass",
    "compose-material-material2"
]

androidx-compose-testImplementation = [
    "compose-ui-test-unit"
]

androidx-compose-androidTestImplementation = [
    "compose-ui-test-junit"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
google-playservices = { id = "com.google.gms.google-services", version.ref = "googlePlayServices" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
versions-plugin = { id = "com.github.ben-manes.versions", version.require = "0.47.0" }
kmpNativeCoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmpNativeCoroutines" }
testLogger = { id = "com.adarshr.test-logger", version.require = "3.2.0" }
ricklephas-kmp-nativeCoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.require = "0.13.3" }
