name: Publish to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macOs-latest
    timeout-minutes: 30
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      SIGNING_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create GPG secring file
        run: |
          mkdir ~/.gnupg
          cd ~/.gnupg
          echo $GPG_KEY > secring.txt
          base64 -i secring.txt -o secring.gpg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add MavenCentral credentials to gradle.properties file
        run: ./scripts/secrets.sh

      - name: Fire in the hole
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-parallel --no-daemon
