name: Publish to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: macOs-latest
    timeout-minutes: 30
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: List keys
        run: gpg -K

#      - name: Configure GPG Key
#        run: |
#          mkdir ~/.gpgkey
#          echo $GPG_KEY > ~/.gpgkey/secring.gpg.b64
#          base64 -d ~/.gpgkey/secring.gpg.b64 > ~/.gpgkey/secring.gpg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add MavenCentral credentials to gradle.properties file
        run: ./scripts/secrets.sh

      - name: Fire in the hole
        run: |
          ./gradlew publishToMavenCentral --no-parallel --no-daemon -Psigning.keyId=${{secrets.GPG_KEY_ID}} -Psigning.password=${{secrets.GPG_KEY_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gnupg/secring.gpg)
