name: Publish to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  maven_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # The entire job will time out after 30 minutes
    env:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg
          echo "$GPG_KEY" > ~/.gnupg/secring.gpg.b64
          base64 -d ~/.gnupg/secring.gpg.b64 > ~/.gnupg/secring.gpg

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add MavenCentral credentials to gradle.properties file
        run: ./scripts/secrets.sh

      - name: Fire in the hole
        run: |
          ./gradlew publishToMavenCentral --no-parallel --no-daemon -Psigning.keyId=${{secrets.GPG_KEY_ID}} -Psigning.password=${{secrets.GPG_KEY_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gnupg/secring.gpg)