name: Update Version Code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  workflow_dispatch:
  schedule:
    # At 00:30am every week on a sunday
    - cron: '30 0 * * 0'

jobs:
  updateversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Bump Version Code
        run: ./gradlew incrementVersionCode

      - name: Set current date as environment variable
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - name: Print current date
        run: echo ${{env.NOW}}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Bump android version code to ${{env.NOW}}
          token: ${{secrets.SECRET_GITHUB}}
          title: Bump Android Version Code to ${{env.NOW}}
          body: Beep boop. Hey there, I have just incremented the version code

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.SECRET_GITHUB }}
          delete-branch: true
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
